name: jupyter_env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - numpy
  - pandas
  - python>=3.7
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels

